---
# file: 01-setup-new-hosts.yaml
- hosts: "{{ target }}"
  vars:
    ansible_ssh_pass: "{{ setup_ssh_password }}"
    ansible_become_pass: "{{ setup_ssh_password }}"
    ansible_update_setup_user_password: false
    ansible_ssh_user: "{{ setup_user }}"
    new_setup_ssh_password: "{{ vault_new_setup_ssh_password | default(setup_ssh_password) }}"
  remote_user: "{{ setup_user }}"
  become: false

  roles:
    - ansible-role-common
