---
# file: 01-setup-new-hosts.yaml
- hosts: all
  vars:
    ansible_ssh_pass: "{{ setup_ssh_password }}"
    ansible_become_pass: "{{ setup_ssh_password }}"
    ansible_update_setup_user_password: false
  remote_user: "{{ setup_user }}"
  become: false

  roles:
    - ansible-role-common
