---
# file: main.yaml
- hosts: all
  #vars:
  #  ansible_ssh_pass: "{{ setup_ssh_password }}"
  #  ansible_become_pass: "{{ setup_ssh_password }}"
  #  ansible_update_setup_user_password: false
  #  ansible_ssh_user: "{{ setup_user }}"
  #remote_user: "{{ setup_user }}"
  become: true
  roles:
    - geerlingguy.docker
  tasks:
    - name: Add all users to the docker group
      user:
        name: user
        groups:
        - docker

