# check inventory for CVE-2019-11815 vulnerability. 
# An issue was discovered in rds_tcp_kill_sock in net/rds/tcp.c in the Linux kernel before 5.0.8. There is a race condition leading to a use-after-free, related to net namespace cleanup.
#
# https://nvd.nist.gov/vuln/detail/CVE-2019-11815

- hosts: all
  tasks:
    
    - name: "Check for rds_tcp module if Kernel version is known to be vulnerable"
      command: grep -Fq "rds_tcp" /proc/modules
      register: rds_module
      check_mode: no
      ignore_errors: yes
      changed_when: no
      when: ansible_kernel is version('5.0.8', '<')
      tags: [ 'always' ]

    - name: "show message if vulnerable"
      debug: 
        msg: "Vulnerable host: {{ ansible_host }} {{ ansible_kernel }}"
      when: rds_module.rc == 0
      tags: [ 'always' ]

    - name: Blacklist rds_tcp
      copy:
        content: |
          # rds_tcp is potental security issue, blacklisting to prevent accidental
          # loading. CVE-2019-11815
          blacklist rds_tcp
          install rds_tcp /bin/true
        dest: /etc/modprobe.d/rds-tcp-blacklist.conf
      when: rds_module.rc == 0
      tags: [ 'never', 'fix' ]  
